### PR TITLE
explicitly define the text color

### PR DESCRIPTION
**Pull request by fenril058**
Probably this pull request is related to "Issues with colors in edit mode #177". When I used the editable plugin with adoradark template, edit table mode show me the white background and nearly white text color which is the same as the @ini_text in the template. To avoid this situation, I add the definition of the text color explicitly.

### CODE REVIEW

**Comment by splitbrain** [comment]
Why is the handsontable.less changed so much?

**Comment by fenril058** [comment]
Oops. I completely destroyed the indent style. That is the reason that too many changes. Sorry. What I want to add is just one line; '''color: #222;''' between the line 174 and 175 of the original handsontable.less. Can I close this pull request and make a new pull request again?

**Comment by splitbrain** [comment]
Sure, either force push to this branch or open a new pull request. I would prefer not to have any changes in the handsontable.less file because it comes from upstream. Better put all customizations in the `less/*` files and use specificity to override the defaults.

**Comment by asheenlevrai** [comment]
Hi :)

I am not sure if this issue is solved in any way currently. Please let me know of to solve the "white text on wheite background" issue if this is the case.

Thank a lot.

Best,
-a-

**Comment by asheenlevrai** [comment]
Any update on this topic?

**Pull request closed without merging**
